name: CI MacOS

on:
  workflow_dispatch:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  build_and_test:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "Main tests"
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain:
          - stable
        feature:
          - serial
          - parallel
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install macfuse
    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
    - name: Setup Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose --features "${{ matrix.feature }} libfuse"
    - name: Run tests
      run: cargo test --verbose --features "${{ matrix.feature }} libfuse"
